/**
 * Mocking client-server processing
 */
// const _products = [
//   {"id": 1, "title": "iPad 4 Mini", "price": 500.01, "inventory": 2},
//   {"id": 2, "title": "H&M T-Shirt White", "price": 10.99, "inventory": 10},
//   {"id": 3, "title": "Charli XCX - Sucker CD", "price": 19.99, "inventory": 5}
// ]
const _products = [
  {
    id: 1,
    title: "Innisfree",
    brand: "Innisfree",
    name: "Sữa rửa mặt innisfree trà xanh Green Tea Cleansing Foam",
    description:
      "Sữa rửa mặt Innisfree Green Tea Cleansing Foam chứa chiết xuất 88% từ lá trà xanh tự nhiên, giàu độ ẩm và các thành phần chống oxi hoá, giúp làm sạch bụi bẩn và các tạp chất trên da, hút nhờn và ngăn ngừa những dấu hiệu làm lão hoá da. Đặc biệt phù hợp với da dầu và có mụn. Đây là sản phẩm sữa rửa mặt chất lượng được ưa chuộng nhất hiện nay. ",
    price: "180.000",
    category: "srm",
    suitable: "dadau",
    status: "0",
    sale: false,
    img: "/img/product/srm/srm1.jpg",
    inventory: 15,
  },
  {
    id: 2,
    title: "Innisfree",
    brand: "Innisfree",
    name: "Sữa Rửa Mặt Innisfree Jeju Cherry Blossom",
    description:
      "A toner filled with 90.97% Rose Water refreshes, soothes and hydrates skin texture. Bulgarian Rose Flower Water, an ingredient that is antibacterial, antimicrobial and anti-inflammatory, soothes irritation, minimise pores and boosts hydration. The rose-scented toner has a lightweight, watery texture that absorbs almost instantly for a plumping and calming effect. The multi-purpose toner can be applied as a toner mask, mist, layered on the skin or as a wipe-off toner. It is free of mineral oil, urea and animal-cruelty and suits all types.",
    price: "230.000",
    category: "srm",
    suitable: "dathuong",
    status: "0",
    sale: true,
    img: "/img/product/srm/srm2.webp",
    inventory: 20,
  },
  {
    id: 3,
    title: "La Roche-Posay",
    brand: "La Roche-Posay",
    name: "Sữa Rửa Mặt La Roche-Posay Effaclar 50ml",
    description:
      "Effaclar Micro Peeling Gel chứa các thành phần giúp thanh lọc & tẩy tế bào chết, giúp làm sạch bã nhờn dư thừa, thông thoáng lỗ chân lông, giảm các khiếm khuyết trên da bao gồm mụn sưng viêm, thâm sau mụn & ngăn ngừa mụn tái phát. Dành cho da mặt và cơ thể.",
    price: "230.000",
    category: "srm",
    suitable: "dathuong",
    status: "0",
    sale: false,
    img: "/img/product/srm/srm3.jpg",
    inventory: 20,
  },
  {
    id: 4,
    title: "Cosrx",
    brand: "Cosrx",
    name: "Sữa Rửa Mặt Cosrx Low PH Morning Gel Cleanser",
    description:
      "- Với độ pH 5.0 – 6.0, sản phẩm giúp da sạch sâu mà không hề gây cảm giác khô căng, khôi phục lại sự cân bằng pH tối ưu cho da mà không gây kích ứng Sản phẩm an toàn mà mang lại hiệu quả cho mọi làn da ngay cả làn da nhạy cảm và da mụn. ",
    price: "230.000",
    category: "srm",
    suitable: "dadau",
    status: "12",
    sale: true,
    img: "/img/product/srm/srm4.jpg",
    inventory: 20,
  },
  {
    id: 5,
    title: "Cosrx",
    brand: "Cosrx",
    name: "Sữa Rửa Mặt Cosrx Cica Cleanser",
    description:
      "Công thức với CICA-7 Complex và Pinus Pinaster Bark Extract, công thức cô đặc cao này mang lại cho làn da hiệu quả làm dịu gấp ba giúp phục hồi và làm khỏe làn da yếu, phá vỡ vòng luẩn quẩn của tổn thương lặp đi lặp lại và làm dịu tạm thời làn da nhạy cảm.",
    price: "230.000",
    category: "srm",
    suitable: "dahhthiendau",
    status: "12",
    sale: false,
    img: "/img/product/srm/srm5.jpg",
    inventory: 20,
  },
  {
    id: 6,
    title: "Cerave",
    brand: "Cerave",
    name: "Sữa Rửa Mặt CeraVe Renewing SA Cleanser",
    description:
      "Công thức với CICA-7 Complex và Pinus Pinaster Bark Extract, công thức cô đặc cao này mang lại cho làn da hiệu quả làm dịu gấp ba giúp phục hồi và làm khỏe làn da yếu, phá vỡ vòng luẩn quẩn của tổn thương lặp đi lặp lại và làm dịu tạm thời làn da nhạy cảm.",
    price: "350.000",
    category: "srm",
    suitable: "dathuong",
    status: "12",
    sale: false,
    img: "/img/product/srm/srm6.jpg",
    inventory: 20,
  },
  {
    id: 7,
    title: "Cosrx",
    brand: "Cosrx",
    name: "Sữa Rửa Mặt Cosrx Calming Foam Cleanser 150ml",
    description:
      "- Dành cho những làn da nhạy cảm và dễ kích ứng. Không gây kích ứng và tổn thương cho da. Sử dụng được cả sáng và tối.",
    price: "240.000",
    category: "srm",
    suitable: "danhaycam",
    status: "12",
    sale: false,
    img: "/img/product/srm/srm7.jpg",
    inventory: 20,
  },
  {
    id: 8,
    title: "Innisfree",
    brand: "Innisfree",
    name: "Sữa Rửa Mặt Innisfree Blueberry Rebalancing 5.5",
    description:
      "Giúp đào thải lượng dầu thừa và bụi bẩn, làm sạch da. Da khỏe mạnh do hoạt động chống oxi hóa của quả việt quất. Dưỡng sáng và làm đều màu da. Giúp cần bằng độ pH cho làn da",
    price: "160.000",
    category: "srm",
    suitable: "dathuong",
    status: "2356",
    sale: true,
    img: "/img/product/srm/srm8.jpg",
    inventory: 10,
  },
  {
    id: 9,
    title: "Cerave",
    brand: "Cerave",
    name: "Sữa Rửa Mặt Cerave Foaming Facial Cleanser",
    description:
      "Được phát triển bởi bác sĩ da liễu tại Mỹ. Sản phẩm được khuyên dùng hàng ngày vì độ dịu nhẹ cũng như khả năng làm sạch da lý tưởng. Độ pH ở mức tốt xấp xỉ 5.5 an toàn cho da. Công thức không gây mụn, không làm tắc nghẽn chân lông, không chứa hương liệu",
    price: "430.000",
    category: "srm",
    suitable: "danhaycam",
    status: "123456",
    sale: true,
    img: "/img/product/srm/srm9.jpg",
    inventory: 20,
  },
  {
    id: 10,
    title: "La Roche-Posay",
    brand: "La Roche-Posay",
    name: "Gel Rửa Mặt La Roche-Posay",
    description:
      "Làm sạch là điều kiện tiên quyết để chăm sóc và bảo vệ làn da. Gel Rửa Mặt La Roche-Posay Effaclar Gel Moussant Purifiant là sản phẩm chuyên biệt dành cho làn da dầu, nhạy cảm giúp loại bỏ bụi bẩn, tạp chất, thúc đẩy việc loại bỏ bã nhờn dư thừa với tinh chất tạo bọt nhẹ nhàng mang đến làn da tươi sáng, thoáng mát",
    price: "115.000",
    category: "srm",
    suitable: "danhaycam",
    status: "126",
    sale: false,
    img: "/img/product/srm/srm10.webp",
    inventory: 10,
  },
  {
    id: 11,
    title: "Obagi",
    brand: "Obagi",
    name: "Dung Dịch Trị Mụn Obagi Medical Salicylic Acid",
    description:
      "Obagi Medical Salicylic Acid 2% Acne Treatment là dung dịch đặc trị giúp sạch sâu lỗ chân lông, làm sạch da của bạn. Thành phần tẩy tế bào chết trong sản phẩm nhẹ nhàng tẩy tế bào chết làm tắc lỗ chân lông, ngăn cản quá trình phục hồi của làn da. Sử dụng sản phẩm sau khi rửa mặt giúp da hấp thu hiệu quả bước điều trị mụn tiếp theo. Da sẽ sạch sâu và lỗ chân lông thu nhỏ nhờ Dung Dịch Trị Mụn Obagi Medical Salicylic Acid 2% Acne Treatment 148ml",
    price: "780.000",
    category: "toner",
    suitable: "dadau",
    status: "126",
    sale: false,
    img: "/img/product/toner/toner2.jpg",
    inventory: 2,
  },
  {
    id: 12,
    title: "Klairs",
    brand: "Klairs",
    name: "Nước Dưỡng Klairs Daily Skin Hydrating Water",
    description:
      "Nước Cân Bằng Klairs Trà Xanh Cấp Ẩm Làm Dịu Da Daily Skin Hydrating Water 500ml là dòng nước hoa hồng đến từ thương hiệu mỹ phẩm Klairs của Hàn Quốc, với thành phần chứa 45% nước trà xanh giúp làm diu da hiệu quả, tăng cường độ ẩm, chống oxy hóa tạo hàng rào bảo vệ da",
    price: "390.000",
    category: "toner",
    suitable: "dakho",
    status: "126",
    sale: false,
    img: "/img/product/toner/toner1.jpg",
    inventory: 8,
  },
  {
    id: 13,
    title: "Innisfree",
    brand: "Innisfree",
    name: "Nước Cân Bằng Innisfree Bija Trouble Skin",
    description:
      "Nước hoa hồng Innisfree Bija Trouble Skin được chiết xuất từ quả nhục đậu khấu được nuôi trồng tại đảo Jeju. Từ xa xưa ở Hàn quốc quả nhục đậu khấu đã được dùng làm nguyên liệu quý trong đông y và dân gian để dâng lên vua với thành phần Salicylic acid và rượu tự nhiên cùng một số các loại thảo mộc xanh tự nhiên khác, hoàn toàn lành tính với da, đặc biệt chuyên dùng cho da dầu có mụn hoặc vùng có khí hậu ẩm ướt. Làn da bạn sẽ trở nên căng mịn khoẻ mạnh ngay sau khi sử dụng.",
    price: "300.000",
    category: "toner",
    suitable: "dadau",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner3.jpg",
    inventory: 3,
  },
  {
    id: 14,
    title: "Cosrx",
    brand: "Cosrx",
    name: "Nước Cân Bằng Cosrx AHA BHA Vitamin C",
    description:
      "Nước cân bằng làm sáng da Cosrx AHA BHA Vitamin C Daily Toner chứa hoạt chất thanh lọc AHA, BHA cùng phức hợp kiwi vàng sẽ mang lại diện mạo mới cho làn da, với tác dụng thanh lọc bề mặt, cân bằng độ pH đồng thời làm tươi sáng những vùng da có đốm nâu, xỉn màu.",
    price: "130.000",
    category: "toner",
    suitable: "all",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner4.jpg",
    inventory: 1,
  },
  {
    id: 15,
    title: "Senka",
    brand: "Senka",
    name: "Nước Cân Bằng Senka Deep Moist Lotion I Dưỡng Ẩm Chuyên Sâu 200ml",
    description:
      "Nước dưỡng cân bằng độ pH và cung cấp độ ẩm, giúp da ẩm mịn và đàn hồi. Thành phần thiên nhiên Tơ Tằm Trắng, Cám Gạo, Mật Ong và gấp đôi Hyaluronic Acid & Collagen không chỉ cấp ẩm tức thì mà còn duy trì cho làn da luôn ẩm mịn và căng mướt cả ngày, cải thiện nếp nhăn, làm mờ vết chân chim, hạn chể tình trạng chảy xệ.",
    price: "160.000",
    category: "toner",
    suitable: "dathuong",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner5.webp",
    inventory: 2,
  },
  {
    id: 16,
    title: "Hada Labo",
    brand: "Hada Labo",
    name: "Dung dịch dưỡng ẩm 170ml (da thường)",
    description:
      "Hệ dưỡng ẩm sâu HA (Hyaluronic Acid) giúp bổ sung nước, giữ nước, ngậm nước cho da luôn ẩm mượt. Dung dịch dưỡng ẩm Hada Labo cung cấp độ ẩm tối ưu cho da, tăng cường độ đàn hồi và duy trì màng ẩm tự nhiên.",
    price: "185.000",
    category: "toner",
    suitable: "all",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner6.png",
    inventory: 2,
  },
  {
    id: 17,
    title: "Ponds",
    brand: "Ponds",
    name: "Nước Hoa Hồng PondS White Beauty Lightening Toner Làm Sáng Da 150ml",
    description:
      "Nước Hoa Hồng PondS White Beauty Lightening Toner Làm Sáng Da với thành phần giàu chất chống oxy hóa và dưỡng chất thiên nhiên, nước hoa hồng làm trắng da Ponds White Beauty nhẹ nhàng làm sạch bụi bẩn, bã nhờn và cặn trang điểm còn sót lại trên da, đồng thời se khít lỗ chân lông và cân bằng độ ẩm cho da luôn sạch mịn. Sản phẩm có công thức dịu nhẹ, phù hợp với mọi làn da.",
    price: "55.000",
    category: "toner",
    suitable: "dathuong",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner7.webp",
    inventory: 2,
  },
  {
    id: 18,
    title: "La Roche-Posay",
    brand: "La Roche-Posay",
    name: "Nước cân bằng dành cho da nhạy cảm La Roche-Posay Soothing Lotion Sensitive Skin 200ml",
    description:
      "Nước cân bằng giàu khoáng dành cho da nhạy cảm La Roche-Posay Soothing Lotion Sensitive Skin với thành phần Selenium giúp làm dịu, bảo vệ và chống oxy hóa.",
    price: "350.000",
    category: "toner",
    suitable: "danhaycam",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner8.jpg",
    inventory: 2,
  },
  {
    id: 19,
    title: "Klairs",
    brand: "Klairs",
    name: "Nước Cân Bằng Klairs Supple Preparation",
    description:
      "Nước Hoa Hồng Không Mùi Dear Klairs Dưỡng Ẩm Da Và Làm Mềm Da Supple Preparation Unscented 180ml có chiết xuất từ thực vật, giúp cân bằng độ pH, tăng cường hiệu quả chăm sóc da Toner có dạng trong suốt, không màu, lỏng, nhẹ, hơi nhớt, thấm rất nhanh trên da. Sản phẩm giúp loại bỏ bụi bẩn và bã nhờn dư thừa trên da sau khi rửa mặt đồng thời cân bằng độ pH để các bước skincare tiếp theo đạt hiệu quả hơn.",
    price: "280.000",
    category: "toner",
    suitable: "all",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner9.jpg",
    inventory: 2,
  },
  {
    id: 20,
    title: "Hatomugi",
    brand: "Another",
    name: "Nước Cân Bằng Hatomugi The Lotion Moisturizing",
    description:
      "Nước Cân Bằng Hatomugi The Lotion Moisturizing & Conditioning 500ml - Hạt ý dĩ Nhật Bản được mệnh danh là thần dược của làn da, với công dụng tuyệt vời làm sạch sâu lỗ chân lông, cấp ẩm, cân bằng độ PH, cho da sáng hồng tự nhiên. Đây cũng là bí quyết làm đẹp của đa phần Phụ Nữ Nhật, với đặc trưng như nước vo gạo, không mùi, thẩm thấu rất nhanh và không nhờn dính, phù hợp kể cả làn da nhạy cảm.",
    price: "265.000",
    category: "toner",
    suitable: "all",
    status: "12",
    sale: false,
    img: "/img/product/toner/toner10.jpg",
    inventory: 2,
  },
];

export default {
  getProducts(cb) {
    setTimeout(() => cb(_products), 100);
  },
};
